resolver: lts-7.10
packages:
- '.'
extra-deps:
- servant-0.9.1.1
- servant-server-0.9.1.1
- servant-client-0.9.1.1
- servant-docs-0.9.1.1
- servant-js-0.9
- servant-foreign-0.9.1
- servant-quickcheck-0.0.2.2
- http-api-data-0.3.3

flags: {}
extra-package-dbs: []
